import type { ProductData, OrderDetail } from "./types"

// 모의 상품 데이터
export const mockProducts: Partial<ProductData>[] = [
  {
    id: "prod-001",
    title: "프리미엄 스마트폰 케이스 도매 (100개 단위)",
    originalPrice: 450000,
    imageUrl: "/bulk-smartphone-cases.png",
  },
  {
    id: "prod-002",
    title: "여성용 캐주얼 티셔츠 OEM 생산 (50개 단위)",
    originalPrice: 380000,
    imageUrl: "/diverse-casual-tees.png",
  },
  {
    id: "prod-003",
    title: "LED 스마트 조명 도매 (20개 단위)",
    originalPrice: 520000,
    imageUrl: "/smart-lighting-warehouse.png",
  },
  {
    id: "prod-004",
    title: "주방용품 세트 OEM 생산 (30세트)",
    originalPrice: 680000,
    imageUrl: "/stainless-steel-utensil-display.png",
  },
  {
    id: "prod-005",
    title: "유아용 장난감 도매 (200개 단위)",
    originalPrice: 420000,
    imageUrl: "/colorful-baby-toy-assortment.png",
  },
  {
    id: "prod-006",
    title: "블루투스 이어폰 OEM 생산 (100개 단위)",
    originalPrice: 950000,
    imageUrl: "/bulk-bluetooth-earphones.png",
  },
  {
    id: "prod-007",
    title: "패션 선글라스 도매 (50개 단위)",
    originalPrice: 320000,
    imageUrl: "/trendy-sunglasses-display.png",
  },
  {
    id: "prod-008",
    title: "스마트 워치 OEM 생산 (30개 단위)",
    originalPrice: 1250000,
    imageUrl: "/smartwatch-display.png",
  },
  {
    id: "prod-009",
    title: "고급 가죽 지갑 도매 (100개 단위)",
    originalPrice: 580000,
    imageUrl: "/assorted-leather-wallets.png",
  },
  {
    id: "prod-010",
    title: "홈 인테리어 소품 도매 (50개 단위)",
    originalPrice: 420000,
    imageUrl: "/placeholder.svg?height=400&width=400&query=home decor items wholesale",
  },
  {
    id: "prod-011",
    title: "스포츠 용품 도매 (30개 단위)",
    originalPrice: 750000,
    imageUrl: "/placeholder.svg?height=400&width=400&query=sports equipment wholesale",
  },
  {
    id: "prod-012",
    title: "화장품 OEM 생산 (200개 단위)",
    originalPrice: 1100000,
    imageUrl: "/placeholder.svg?height=400&width=400&query=cosmetics wholesale",
  },
]

// 모의 주문 목록 데이터
export const mockOrders = [
  {
    id: "order-1",
    productId: "prod-001",
    productTitle: "프리미엄 스마트폰 케이스 도매 (100개 단위)",
    status: "배송 완료",
    orderDate: "2023-11-15",
    totalAmount: 585000,
    imageUrl: "/bulk-smartphone-cases.png",
  },
  {
    id: "order-2",
    productId: "prod-003",
    productTitle: "LED 스마트 조명 도매 (20개 단위)",
    status: "배송중",
    orderDate: "2023-12-05",
    totalAmount: 676000,
    imageUrl: "/smart-lighting-warehouse.png",
  },
  {
    id: "order-3",
    productId: "prod-002",
    productTitle: "여성용 캐주얼 티셔츠 OEM 생산 (50개 단위)",
    status: "배송 준비중",
    orderDate: "2024-01-20",
    totalAmount: 494000,
    imageUrl: "/diverse-casual-tees.png",
  },
  {
    id: "order-4",
    productId: "prod-004",
    productTitle: "주방용품 세트 OEM 생산 (30세트)",
    status: "관리자 승인 대기",
    orderDate: "2024-02-10",
    totalAmount: 884000,
    imageUrl: "/stainless-steel-utensil-display.png",
  },
  {
    id: "order-5",
    productId: "prod-006",
    productTitle: "블루투스 이어폰 OEM 생산 (100개 단위)",
    status: "결제 대기",
    orderDate: "2024-02-15",
    totalAmount: 1235000,
    imageUrl: "/bulk-bluetooth-earphones.png",
  },
  {
    id: "order-6",
    productId: "prod-009",
    productTitle: "고급 가죽 지갑 도매 (100개 단위)",
    status: "주문 취소",
    orderDate: "2024-01-05",
    totalAmount: 754000,
    imageUrl: "/assorted-leather-wallets.png",
  },
  {
    id: "order-7",
    productId: "prod-012",
    productTitle: "화장품 OEM 생산 (200개 단위)",
    status: "배송 완료",
    orderDate: "2023-10-25",
    totalAmount: 1430000,
    imageUrl: "/placeholder.svg?height=400&width=400&query=cosmetics wholesale",
  },
  {
    id: "order-8",
    productId: "prod-008",
    productTitle: "스마트 워치 OEM 생산 (30개 단위)",
    status: "배송중",
    orderDate: "2024-02-01",
    totalAmount: 1625000,
    imageUrl: "/smartwatch-display.png",
  },
]

// 모의 주문 상세 데이터
export const mockOrderDetails: OrderDetail[] = [
  {
    id: "order-1",
    status: "배송 완료",
    orderDate: "2023-11-15",
    estimatedDeliveryDate: "2023-11-30",
    trackingNumber: "KR123456789",
    totalAmount: 585000,
    product: {
      id: "prod-001",
      title: "프리미엄 스마트폰 케이스 도매 (100개 단위)",
      platform: "Alibaba",
      originalPrice: 450000,
      estimatedPrice: 585000,
      imageUrl: "/bulk-smartphone-cases.png",
      fees: 22500,
      tax: 36000,
      shippingCost: 25000,
      originalUrl: "https://alibaba.com/product/prod-001",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
      requestNote: "부재시 경비실에 맡겨주세요.",
    },
    paymentMethod: "신용카드",
    history: [
      {
        date: "2023-11-15",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2023-11-16",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2023-11-16",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2023-11-20",
        status: "상품 준비중",
        description: "상품을 준비 중입니다.",
      },
      {
        date: "2023-11-25",
        status: "배송 시작",
        description: "상품이 배송지로 출발했습니다.",
      },
      {
        date: "2023-11-30",
        status: "배송 완료",
        description: "상품이 배송지에 도착했습니다.",
      },
    ],
  },
  {
    id: "order-2",
    status: "배송중",
    orderDate: "2023-12-05",
    estimatedDeliveryDate: "2023-12-20",
    trackingNumber: "KR987654321",
    totalAmount: 676000,
    product: {
      id: "prod-003",
      title: "LED 스마트 조명 도매 (20개 단위)",
      platform: "Alibaba",
      originalPrice: 520000,
      estimatedPrice: 676000,
      imageUrl: "/smart-lighting-warehouse.png",
      fees: 26000,
      tax: 41600,
      shippingCost: 30000,
      originalUrl: "https://alibaba.com/product/prod-003",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
    },
    paymentMethod: "계좌이체",
    history: [
      {
        date: "2023-12-05",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2023-12-06",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2023-12-06",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2023-12-10",
        status: "상품 준비중",
        description: "상품을 준비 중입니다.",
      },
      {
        date: "2023-12-15",
        status: "배송 시작",
        description: "상품이 배송지로 출발했습니다.",
      },
    ],
  },
  {
    id: "order-3",
    status: "배송 준비중",
    orderDate: "2024-01-20",
    totalAmount: 494000,
    product: {
      id: "prod-002",
      title: "여성용 캐주얼 티셔츠 OEM 생산 (50개 단위)",
      platform: "Taobao",
      originalPrice: 380000,
      estimatedPrice: 494000,
      imageUrl: "/diverse-casual-tees.png",
      fees: 19000,
      tax: 30400,
      shippingCost: 22000,
      originalUrl: "https://taobao.com/product/prod-002",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
      requestNote: "문 앞에 놓아주세요.",
    },
    paymentMethod: "신용카드",
    history: [
      {
        date: "2024-01-20",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2024-01-21",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2024-01-21",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2024-01-25",
        status: "상품 준비중",
        description: "상품을 준비 중입니다.",
      },
    ],
  },
  {
    id: "order-4",
    status: "관리자 승인 대기",
    orderDate: "2024-02-10",
    totalAmount: 884000,
    product: {
      id: "prod-004",
      title: "주방용품 세트 OEM 생산 (30세트)",
      platform: "Alibaba",
      originalPrice: 680000,
      estimatedPrice: 884000,
      imageUrl: "/stainless-steel-utensil-display.png",
      fees: 34000,
      tax: 54400,
      shippingCost: 35000,
      originalUrl: "https://alibaba.com/product/prod-004",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
    },
    paymentMethod: "",
    history: [
      {
        date: "2024-02-10",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
    ],
  },
  {
    id: "order-5",
    status: "결제 대기",
    orderDate: "2024-02-15",
    totalAmount: 1235000,
    product: {
      id: "prod-006",
      title: "블루투스 이어폰 OEM 생산 (100개 단위)",
      platform: "1688",
      originalPrice: 950000,
      estimatedPrice: 1235000,
      imageUrl: "/bulk-bluetooth-earphones.png",
      fees: 47500,
      tax: 76000,
      shippingCost: 40000,
      originalUrl: "https://1688.com/product/prod-006",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
    },
    paymentMethod: "",
    history: [
      {
        date: "2024-02-15",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2024-02-16",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
    ],
  },
  {
    id: "order-6",
    status: "주문 취소",
    orderDate: "2024-01-05",
    totalAmount: 754000,
    product: {
      id: "prod-009",
      title: "고급 가죽 지갑 도매 (100개 단위)",
      platform: "Alibaba",
      originalPrice: 580000,
      estimatedPrice: 754000,
      imageUrl: "/assorted-leather-wallets.png",
      fees: 29000,
      tax: 46400,
      shippingCost: 28000,
      originalUrl: "https://alibaba.com/product/prod-009",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
    },
    paymentMethod: "신용카드",
    history: [
      {
        date: "2024-01-05",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2024-01-06",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2024-01-06",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2024-01-08",
        status: "주문 취소 요청",
        description: "고객님의 요청으로 주문 취소가 요청되었습니다.",
      },
      {
        date: "2024-01-09",
        status: "주문 취소",
        description: "주문이 취소되었습니다. 환불이 진행됩니다.",
      },
    ],
  },
  {
    id: "order-7",
    status: "배송 완료",
    orderDate: "2023-10-25",
    estimatedDeliveryDate: "2023-11-10",
    trackingNumber: "KR456789123",
    totalAmount: 1430000,
    product: {
      id: "prod-012",
      title: "화장품 OEM 생산 (200개 단위)",
      platform: "Alibaba",
      originalPrice: 1100000,
      estimatedPrice: 1430000,
      imageUrl: "/placeholder.svg?height=400&width=400&query=cosmetics wholesale",
      fees: 55000,
      tax: 88000,
      shippingCost: 45000,
      originalUrl: "https://alibaba.com/product/prod-012",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
    },
    paymentMethod: "가상계좌",
    history: [
      {
        date: "2023-10-25",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2023-10-26",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2023-10-26",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2023-10-30",
        status: "상품 준비중",
        description: "상품을 준비 중입니다.",
      },
      {
        date: "2023-11-05",
        status: "배송 시작",
        description: "상품이 배송지로 출발했습니다.",
      },
      {
        date: "2023-11-10",
        status: "배송 완료",
        description: "상품이 배송지에 도착했습니다.",
      },
    ],
  },
  {
    id: "order-8",
    status: "배송중",
    orderDate: "2024-02-01",
    estimatedDeliveryDate: "2024-02-20",
    trackingNumber: "KR789123456",
    totalAmount: 1625000,
    product: {
      id: "prod-008",
      title: "스마트 워치 OEM 생산 (30개 단위)",
      platform: "Alibaba",
      originalPrice: 1250000,
      estimatedPrice: 1625000,
      imageUrl: "/smartwatch-display.png",
      fees: 62500,
      tax: 100000,
      shippingCost: 50000,
      originalUrl: "https://alibaba.com/product/prod-008",
    },
    shipping: {
      name: "테스트 사용자",
      phone: "010-1234-5678",
      email: "test@test.com",
      address: "서울특별시 강남구",
      detailAddress: "테헤란로 123",
      zipCode: "06123",
      requestNote: "배송 전 연락 부탁드립니다.",
    },
    paymentMethod: "신용카드",
    history: [
      {
        date: "2024-02-01",
        status: "주문 접수",
        description: "주문이 접수되었습니다.",
      },
      {
        date: "2024-02-02",
        status: "관리자 승인",
        description: "주문이 승인되었습니다.",
      },
      {
        date: "2024-02-02",
        status: "결제 완료",
        description: "결제가 완료되었습니다.",
      },
      {
        date: "2024-02-05",
        status: "상품 준비중",
        description: "상품을 준비 중입니다.",
      },
      {
        date: "2024-02-10",
        status: "배송 시작",
        description: "상품이 배송지로 출발했습니다.",
      },
    ],
  },
]
